### ISSUE TITLE
[Documentation, Readme] Clarification if this works on BG2 EE?

### ISSUE THREAD

**Issue by rubyFeedback** [Gitjas/Ascalons_Questpack#9]
Right now from the README alone I assume only one quest works on BG2 EE. Can the README explicitely confirm this, if you find the time to adjust this? I'd like to know how many of these quests work on BG2 EE.

**Comment by Gitjas** [comment]
The component description in the readme is separated in "Baldur's Gate I" and "Baldur's Gate II", that would be how the components will be installed to the single games (and not EET/BGT). Meaning, "A Halfling among the Eyeless" is the only quest for BGII.

For EET/BGT, the tweaked version of the Serpents of Abbathor (good aligned ending) will have a small follow up in BGII; this only happens if the BG1 quest was solved accordingly.

I didn't mean to sound snobbish, what would you like to see in the readme to make the distinction between BG1 and BGII quests more obvious?

**Comment by Gitjas** [comment]
I added this for v5.2:
"There is 9 components for BG1, and one (component 10: "A Halfling among the Eyeless") for BGII.
Component 9 ("The Serpents of Abbathor"); tweaked version (option 2) has a small follow-up in BG2 if the good path was played in BG1 (BGT and EET only)."
